<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule-1</name>
  <uuid>a8c27a46-6a9b-4676-8478-4d980fb72a08</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    the deliveryDate of 'the order' is before or the same as the orderDate of 'the order'
then
    set decision to "Delivery date of order is less or equal to the Order date." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
