<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>7b0024f1-1ef2-491f-97ab-573c25d64e49</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Allowed" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
