<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Caclulate Order Total</name>
  <uuid>e43238a1-1d9a-4ead-84eb-a0d26bbf0542</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to 0 ;
for each OrderItem called 'item' , in 'the order items' :
 - set decision to decision + ( the Quantity of item * the PricePerUnit of item ) , ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
