<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>output-default-setting</name>
  <uuid>1ad8b25b-32e8-4074-bbdf-c2546463646a</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to "Allowed" ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
