<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>rule-1</name>
  <uuid>a8f33ded-f5c5-47b6-baca-0dc165011e4c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if 'the order total'  is more than 'the customer limit' 
then
set decision to "Order value is more than what is maximum allowed value for this customer, based on it's credit-score and limits." ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
